# ===================================
#  Calendar Behavior Config
# ===================================

# Model to use for getting the records to display on the calendar
modelClass: Author\Plugin\Models\Event

# Calendar Title
title: 'backend::lang.calendar.title'

# Search columns
# Used for configuration of additional columns to search by
searchList: $/author/plugin/models/event/columns.yaml

# Record URL
recordUrl: author/plugins/events/update/:id

# Record property used as the title displayed on the calendar
recordTitle: name

# Record property used as the start time
recordStart: start_at

# Record property used as the end time
recordEnd: end_at

# Record property used as all day long event
recordAllDay: all_day

# Record property used as the background color displayed on the record, , '' = the default background color in the calendar.less
recordColor: event_color

# Record property used as the content of the tooltip
recordTooltip: [recordTitle]

# Calendar widget theme color for buttons ('' for default, primary or secondary)
calendarTheme:

# Available display modes to be supported in this instance
availableDisplayModes: [month, week, day, list]

# Default view for calendar widget (month, week, day or list)
initialView: month

# First day of week, 0=Sun, 1=Mon ...
firstDay: 0

# Flag for whether calendar is read only or editable
previewMode: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: calendar_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

# The filter config file for the controller
filter: calendar_filter.yaml

# when filter gets applied, clear the client's cache of events, essentially start them over
# if they had just loaded this page / month with the current filters applied


# Record on click
# @see custom.calendar.js sample
# data is a plain object with the following properties:
#   startDate: is a JS Date Object
#   endDate: is a JS Date Object, may be null
#   event: A standard JavaScript object that FullCalendar uses to store information about a calendar event, including id, title, start, end
#   eventEl: The HTML element for this event
# recordOnClick: $.wn.eventController.onEventClick(:data, :startDate, :endDate, :event, :eventEl)

# Triggered when the user clicks on a date or a time
# data is a plain object with the following properties
# date: is the a JS Date Object for the clicked day/time.
# dateStr: An ISO8601 string representation of the date
# allDay: true or false
# dayEl: An HTML element that represents the whole-day that was clicked on.
# event: The native JavaScript event with low-level information such as click coordinates.
# view: The current view @see https://fullcalendar.io/docs/v4/view-object
onClickDate: $.wn.availabilitySlotController.onClickDate(:data, :date, :dateStr, :allDay,  :dayEl, :event, :view)

# load one month of records at a time, ensure they stay loaded between month pages
