#!/bin/sh

EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
php -r "copy('https://getcomposer.org/installer', $_SERVER['GITPOD_REPO_ROOT'] . '/composer-setup.php');"
ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', $_SERVER['GITPOD_REPO_ROOT'] . '/composer-setup.php');")"

if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
then
    >&2 echo 'ERROR: Invalid installer checksum'
    rm $GITPOD_REPO_ROOT/composer-setup.php
    exit 1
fi

php $GITPOD_REPO_ROOT/composer-setup.php --quiet
RESULT=$?
rm $GITPOD_REPO_ROOT/composer-setup.php
exit $RESULT
