name: Archive

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 182
        days-before-close: 3
        stale-issue-message: >
          This issue will be closed and archived in 3 days, as there has been no activity in this issue for the last 6 months.

          If this issue is still relevant or you would like to see it actioned, please respond within 3 days.
          
          If this issue is critical for your business, please reach out to us at wintercms@luketowers.ca.
        stale-pr-message: >
          This pull request will be closed and archived in 3 days, as there has been no activity in this pull request for the last 6 months.

          If you intend to continue working on this pull request, please respond within 3 days.
          
          If this pull request is critical for your business, please reach out to us at wintercms@luketowers.ca.
        stale-issue-label: 'Status: Archived'
        stale-pr-label: 'Status: Archived'
        exempt-issue-label: 'Status: In Progress'
        exempt-pr-label: 'Status: In Progress'
