name: Manifest

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  updateManifest:
    name: Update manifest
    runs-on: ubuntu-latest
    env:
      phpVersion: '8.2'
      extensions: curl, fileinfo, gd, mbstring, openssl, pdo, pdo_sqlite, sqlite3, xml, zip
      key: winter-cms-cache-develop
    steps:
      - name: Cancel previous incomplete runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Setup extension cache
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.phpVersion }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.phpVersion }}
          extensions: ${{ env.extensions }}

      - name: Setup dependency cache
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Download manifest
        run: wget -O builds.json https://github.com/wintercms/meta/raw/master/manifest/builds.json

      - name: Run manifest
        run: php artisan winter:manifest builds.json

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: winter-manifest
          path: builds.json
  commitManifest:
    name: Commit manifest
    runs-on: ubuntu-latest
    needs: updateManifest
    steps:
      - name: Cancel previous incomplete runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout changes
        uses: actions/checkout@v3
        with:
          repository: wintercms/meta
          ref: master
          token: ${{ secrets.WINTER_BOT_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: winter-manifest
          path: manifest

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update manifest
          commit_user_name: Winter Bot
          commit_user_email: 80384029+WinterCMSBot@users.noreply.github.com
