name: Module sub-split

on:
  push:
  create:
  delete:

jobs:
    split:
        name: Sub-split
        runs-on: ubuntu-latest
        container: wintercms/cli:0.3.4
        env:
            WINTER_CLI_GITHUB_TOKEN: ${{ secrets.WINTER_SPLIT_TOKEN }}
        steps:
            - name: Create tag
              if: github.event_name == 'create' && github.ref_type == 'tag'
              run: winter split -a "${{ github.ref_name }}"
            - name: Delete branch
              if: github.event_name == 'delete' && github.ref_type == 'branch'
              run: winter split --remove-branch="${{ github.event.ref }}"
            - name: Delete tag
              if: github.event_name == 'delete' && github.ref_type == 'tag'
              run: winter split --remove-tag="${{ github.event.ref }}"
            - name: Push
              if: github.event_name == 'push'
              run: winter split -b "${{ github.ref_name }}"
